### PR TITLE
fix(video-conferencing-service): add reusability

### LINKED ISSUE #307: Video Conference service: extensibility
# Additions
* add basic start meeting ,end meeting and edit meeting. 
* add a provider for pre meeting
* add a provider for post meeting
* add a provider for pre edit 
* add a provider for post edit
# Issues
* the functions should be reusable rather than in the controller
* business logic if any should be moved to a provider for any change.
* update "crypto-random-string" package or use something else in place of it.

### PR DESCRIPTION
**Pull request by parul147**
## Description

issues: 

- the functions should be reusable rather than in the controller
- business logic if any should be moved to a provider for any change.
- update "crypto-random-string" package or use something else in place of it.

Fixes #307
1) Moved the functions in controller to the services(ChatArchiveService and ChatSessionService).
2) Created Provider for crypto-random-string.
3) Business Logic Moved to Services

## How Has This Been Tested?
-Performed Successful unit testing.

## Checklist:
- [x]  Performed a self-review of my own code
- [x] npm test passes on your machine
- [x] New tests added or existing tests modified to cover all changes

### CODE REVIEW

File: sandbox/video-conferencing-ms-example/src/application.ts [hunk 1]
```diff
@@ -26,13 +26,13 @@ export class VideoConferencingExampleApplication extends BootMixin(
...
     dotenvExt.load({
-      schema: '.env.example',
+      schema: '.env',
       errorOnMissing: true,
       includeProcessEnv: true,
     });
     options.rest = options.rest || {};
     options.rest.port = +(process.env.PORT ?? port);
-    options.rest.host = process.env.HOST;
+    options.rest.host = 'localhost';
```
Comment (SouravSF) [inline sandbox/video-conferencing-ms-example/src/application.ts:35]: revert this

File: sandbox/video-conferencing-ms-example/src/application.ts [hunk 2]
```diff
@@ -26,13 +26,13 @@ export class VideoConferencingExampleApplication extends BootMixin(
   constructor(options: ApplicationConfig = {}) {
     dotenv.config();
     dotenvExt.load({
-      schema: '.env.example',
+      schema: '.env',
```
Comment (SouravSF) [inline sandbox/video-conferencing-ms-example/src/application.ts:29]: revert this

File: sandbox/video-conferencing-ms-example/src/datasources/pg.datasource.ts [hunk 3]
```diff
@@ -5,12 +5,12 @@ const config = {
   name: 'videochatDb',
   connector: 'postgresql',
   url: '',
-  host: process.env.DB_HOST,
-  port: process.env.DB_PORT,
-  user: process.env.DB_USER,
-  password: process.env.DB_PASSWORD,
-  database: process.env.DB_DATABASE,
-  schema: process.env.DB_SCHEMA,
+  host: process.env.HOST,
```
Comment (SouravSF) [inline sandbox/video-conferencing-ms-example/src/datasources/pg.datasource.ts:8]: revert these

File: sandbox/pubnub-example/package.json [hunk 4]
```diff
@@ -1,84 +1,55 @@
...
-    "@loopback/build": "^6.4.1",
-    "@loopback/eslint-config": "^10.2.1",
-    "@loopback/testlab": "^3.4.1",
-    "@types/node": "^10.17.60",
-    "eslint": "^7.28.0",
-    "source-map-support": "^0.5.19",
-    "typescript": "~4.3.2"
-  }
+	"name": "@sourceloop/pubnub-example",
+	"version": "0.0.1",
```
Comment (SouravSF) [inline sandbox/pubnub-example/package.json:3]: why did we remove scripts?

File: sandbox/video-conferencing-ms-example/.env.example [hunk 5]
```diff
@@ -1,11 +0,0 @@
-VONAGE_API_KEY=
-VONAGE_API_SECRET=
-TIME_TO_START=
-DB_HOST=
```
Comment (SouravSF) [inline sandbox/video-conferencing-ms-example/.env.example:4]: why did we delete env example file?

File: sandbox/pubnub-example/package.json.lerna_backup [hunk 6]
```diff
@@ -0,0 +1,84 @@
+{
```
Comment (SouravSF) [inline sandbox/pubnub-example/package.json.lerna_backup:1]: the backup file should not be present

File: sandbox/workflow-ms-example/package-lock.json [hunk 7]
```diff
@@ -288,16 +288,6 @@
 				"to-fast-properties": "^2.0.0"
 			}
 		},
```
Comment (SouravSF) [inline sandbox/workflow-ms-example/package-lock.json:290]: why have u pushed package locks for stuff that you have not worked on? remove these changes

Comment (SouravSF) [reply sandbox/workflow-ms-example/package-lock.json:290]: multiple files

File: sandbox/video-conferencing-ms-example/src/application.ts (hunk 2 above)
Comment (parul147) [reply sandbox/video-conferencing-ms-example/src/application.ts:29]: reverting this

File: sandbox/video-conferencing-ms-example/src/datasources/pg.datasource.ts (hunk 3 above)
Comment (parul147) [reply sandbox/video-conferencing-ms-example/src/datasources/pg.datasource.ts:8]: reverting

File: sandbox/pubnub-example/package.json (hunk 4 above)
Comment (parul147) [reply sandbox/pubnub-example/package.json:3]: I did not touch this file, checking this

File: sandbox/video-conferencing-ms-example/.env.example (hunk 5 above)
Comment (parul147) [reply sandbox/video-conferencing-ms-example/.env.example:4]: got it back, had an complication earlier while testing the service

Comment (SouravSF) [reply sandbox/video-conferencing-ms-example/.env.example:4]: I can still see missing vairiabels please add these

File: services/video-conferencing-service/tsconfig.json [hunk 8]
```diff
@@ -2,6 +2,7 @@
   "$schema": "http://json.schemastore.org/tsconfig",
   "extends": "@loopback/build/config/tsconfig.common.json",
   "compilerOptions": {
+   "experimentalDecorators":true,
```
Comment (yeshamavani) [inline services/video-conferencing-service/tsconfig.json:5]: not needed

**Review by yeshamavani — COMMENTED** [review]
not needed

File: services/video-conferencing-service/tsconfig.json (hunk 8 above)
Comment (parul147) [reply services/video-conferencing-service/tsconfig.json]: removed

**Review by yeshamavani — APPROVED** [review]

File: sandbox/pubnub-example/package.json (hunk 4 above)
Comment (parul147) [reply sandbox/pubnub-example/package.json]: Files re-commited, issue rectified

File: sandbox/video-conferencing-ms-example/.env.example (hunk 5 above)
Comment (parul147) [reply sandbox/video-conferencing-ms-example/.env.example]: added the missing variables

File: sandbox/pubnub-example/package.json.lerna_backup (hunk 6 above)
Comment (parul147) [reply sandbox/pubnub-example/package.json.lerna_backup]: done sir

File: sandbox/workflow-ms-example/package-lock.json (hunk 7 above)
Comment (parul147) [reply sandbox/workflow-ms-example/package-lock.json]: commited the wrong way, re-commited and rectified the issue

File: services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-archive.controller.unit.ts [hunk 9]
```diff
@@ -139,19 +134,15 @@ describe('Archive APIs', () => {
       timeToStart: 30,
     };
     videoChatSessionRepo = createStubInstance(VideoChatSessionRepository);
-    auditLogRepo = createStubInstance(AuditLogsRepository);
-    auidtLogCreate = auditLogRepo.stubs.create;
```
Comment (akshatdubeysf) [inline services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-archive.controller.unit.ts:143]: Fix the variable name.

File: services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-session.controller.unit.ts [hunk 10]
```diff
@@ -505,22 +478,53 @@ describe('Session APIs', () => {
...
     videoChatSessionRepo = createStubInstance(VideoChatSessionRepository);
 
-    auditLogRepo = createStubInstance(AuditLogsRepository);
-    auditLogCreate = auditLogRepo.stubs.create;
-    auditLogCreate.resolves();
+    chatSessionService = createStubInstance(ChatSessionService);
 
     sessionAttendeesRepo = createStubInstance(SessionAttendeesRepository);
-
+    const generatorProvider = createStubInstance(
```
Comment (akshatdubeysf) [inline services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-session.controller.unit.ts:484]: These are not needed as you are passing a different generator, not through the provider.

File: services/video-conferencing-service/src/providers/vonage/vonage.provider.ts [hunk 11]
```diff
@@ -14,43 +14,22 @@ import {
...
     private readonly vonageService: VonageService,
-    @repository(AuditLogsRepository)
-    private readonly auditLogRepository: AuditLogsRepository,
   ) {}
   value() {
     return {
       getMeetingLink: async (
         meetingOptions: VonageMeetingOptions,
       ): Promise<VonageMeetingResponse> => {
         try {
```
Comment (akshatdubeysf) [inline services/video-conferencing-service/src/providers/vonage/vonage.provider.ts:30]: Remove try catch from here otherwise all the errors would be wrapped in a InternalServerError, even the BadRequest errors.

File: services/video-conferencing-service/src/component.ts [hunk 12]
```diff
@@ -67,6 +75,24 @@ export class VideoConfServiceComponent implements Component {
       ),
     );
 
+    this.bindings.push(
+      Binding.bind(MeetLinkGeneratorProvider).toProvider(
+        MeetingLinkIdGeneratorProvider,
+      ),
+    );
+
+    this.bindings.push(
```
Comment (akshatdubeysf) [inline services/video-conferencing-service/src/component.ts:84]: Multiple bindings can be added in one push.

File: services/video-conferencing-service/src/component.ts [hunk 13]
```diff
@@ -67,6 +75,24 @@ export class VideoConfServiceComponent implements Component {
       ),
     );
 
+    this.bindings.push(
+      Binding.bind(MeetLinkGeneratorProvider).toProvider(
+        MeetingLinkIdGeneratorProvider,
```
Comment (akshatdubeysf) [inline services/video-conferencing-service/src/component.ts:80]: Use the providers property for providers.

**Review by akshatdubeysf — CHANGES_REQUESTED** [review]

**Comment by akshatdubeysf** [comment]
@parul147 also add the test coverage.

File: services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-session.controller.unit.ts (hunk 10 above)
Comment (parul147) [reply services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-session.controller.unit.ts]: I have removed the unnecessary  lines.

File: services/video-conferencing-service/src/component.ts (hunk 12 above)
Comment (parul147) [reply services/video-conferencing-service/src/component.ts]: Made the required changes. added the bindings in one push.

File: services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-archive.controller.unit.ts (hunk 9 above)
Comment (akshatdubeysf) [reply services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-archive.controller.unit.ts:143]: not an issue, my bad.

**Review by SouravSF — APPROVED** [review]

**Comment by SouravSF** [comment]
@parul147 Please go through the code smells

File: services/video-conferencing-service/src/providers/vonage/vonage.provider.ts (hunk 11 above)
Comment (parul147) [reply services/video-conferencing-service/src/providers/vonage/vonage.provider.ts]: I have made the necessary changes.

File: services/video-conferencing-service/src/component.ts (hunk 13 above)
Comment (parul147) [reply services/video-conferencing-service/src/component.ts]: done

**Review by akshatdubeysf — APPROVED** [review]
