### PR TITLE
fix(authentication-service): provide support to manage tokens for user logging in via Azure

### LINKED ISSUE #1924: Authentication Service: Need support to manage tokens for user logging in via Azure
**Describe the bug**
When a user logs in via Azure , the tokens provided by the Azure are not used , while issuing access tokens tokens using the refresh token. Instead the tokens are internally generated without any consent from Azure
in continuation - https://github.com/sourcefuse/loopback4-microservice-catalog/issues/1263

### PR DESCRIPTION
**Pull request by arpit1503khanna**
## Description

Provide support to manage tokens for user logging in via Azure

Fixes #1924 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: services/authentication-service/src/providers/types.ts [hunk 1]
```diff
@@ -43,6 +43,8 @@ export type GooglePostVerifyFn = (
 ) => Promise<IAuthUser | null>;
 export type AuthenticationProviderFn = (
   accessToken: string,
+  req: AuthRefreshTokenRequest,
+  payload: AnyObject,
```
Comment (yeshamavani) [inline services/authentication-service/src/providers/types.ts:47]: why mandatory
wont this affect other strategies

Comment (arpit1503khanna) [reply services/authentication-service/src/providers/types.ts:47]: But we are sure , that we will get req and payload.
Can u please elaborate further, how it can affect other strategies
@yeshamavani

Comment (yeshamavani) [reply services/authentication-service/src/providers/types.ts:47]: in services/authentication-service/src/providers/google-authentication.provider.ts its added as optional and here its mandatory

File: services/authentication-service/src/providers/azure-authentication.provider.ts [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+    const url = `https://login.microsoftonline.com/${process.env.AZURE_TENANT_ID}/oauth2/v2.0/token`;
+    const clientId = process.env.AZURE_AUTH_CLIENT_ID;
+    const grantType = 'refresh_token';
+    const clientSecret = process.env.AZURE_AUTH_CLIENT_SECRET; // NOTE: Only applicable for web apps
+    const requestBody = `client_id=${clientId}&refresh_token=${refreshToken}&grant_type=${grantType}&client_secret=${clientSecret}`;
+    const refreshPayload = payload.refreshPayload;
+    fetch(url, {
+      method: 'POST',
+      headers: {
+        'Content-Type': 'application/x-www-form-urlencoded',
```
Comment (yeshamavani) [inline services/authentication-service/src/providers/azure-authentication.provider.ts:45]: use the const defined in '@sourceloop/core' for the content-type

Comment (yeshamavani) [reply services/authentication-service/src/providers/azure-authentication.provider.ts:45]: same changes for the remaining providers as well

**Review by yeshamavani — CHANGES_REQUESTED** [review]

**Review by yeshamavani — APPROVED** [review]

**Comment by yeshamavani** [comment]
@arpit1503khanna check the sonar
