### PR TITLE
fix(survey-service): convert survey service migrations in postgresql

### LINKED ISSUE #1782: Survey-service module missing in SL cli
**Describe the bug**
While setting up micro service using sl command line , not able to find survey-service in base services list. 

**To Reproduce**
1. sl microservice <service name>
2. choose base as sourceloop micro-service
3. Scroll down in the list to verify , survey service not found in list , though it is present in git catalog

**Expected behavior**
One should be able to setup survey module using base as sourceloop survey service.

**Screenshots**
Screenshot from 2023-10-25 13-00-44
**Additional Information**
Node version used:18.18.2
SL cli version: 4.2.1

### PR DESCRIPTION
**Pull request by arpit1503khanna**
MIGRATION CHANGE:
migration-20230619123543- convert survey service migrations in postgresql migration-20230619123601- convert survey service migrations in postgresql migration-20230621082309- convert survey service migrations in postgresql migration-20230621113225- convert survey service migrations in postgresql migration-20230621164240- convert survey service migrations in postgresql migration-20230621164337- convert survey service migrations in postgresql migration-20230622111309- convert survey service migrations in postgresql migration-20230622111907- convert survey service migrations in postgresql migration-20230622112026- convert survey service migrations in postgresql migration-20230622112223- convert survey service migrations in postgresql migration-20230622112646- convert survey service migrations in postgresql

## Description
Convert survey service migrations in postgresql

Fixes #1782 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: services/survey-service/migrations/sqls/20230619123543-create-questions-up.sql [hunk 1]
```diff
@@ -1,30 +1,26 @@
...
-    ) NOT NULL,
-    is_score_enabled TINYINT(1) DEFAULT FALSE,
-    is_followup_enabled TINYINT(1) DEFAULT FALSE,
-    root_question_id varchar(50) NULL,
-    parent_question_id varchar(50) NULL,
+    question_type question_type_enum NOT NULL,
+    is_score_enabled BOOLEAN DEFAULT FALSE,
+    is_followup_enabled BOOLEAN DEFAULT FALSE,
+    root_question_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
+    parent_question_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230619123543-create-questions-up.sql:13]: why are we giving default value here ?

File: services/survey-service/migrations/sqls/20230619123543-create-questions-up.sql [hunk 2]
```diff
@@ -1,30 +1,26 @@
...
     modified_on timestamp DEFAULT current_timestamp,
-    deleted TINYINT(1) DEFAULT FALSE,
+    deleted BOOLEAN DEFAULT FALSE,
     created_by varchar(50),
     modified_by varchar(50),
     deleted_on timestamp NULL,
     deleted_by varchar(50),
     ext_id varchar(100),
-    ext_metadata json,
+    ext_metadata jsonb,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230619123543-create-questions-up.sql:23]: why jsonb this might affect the functionality

File: services/survey-service/migrations/sqls/20230619123601-create-question-options-up.sql [hunk 3]
```diff
@@ -1,19 +1,19 @@
...
+    id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
     name VARCHAR(500) NULL,
-    display_order INTEGER(100) NOT NULL,
-    score DECIMAL NULL,
-    followup_question_id varchar(50) NULL,
-    question_id varchar(100) NOT NULL,
+    display_order INTEGER NOT NULL,
+    score DECIMAL(10,0),
+    followup_question_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
+    question_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230619123601-create-question-options-up.sql:7]: again why default value

File: services/survey-service/migrations/sqls/20230619123601-create-question-options-up.sql [hunk 4]
```diff
@@ -1,19 +1,19 @@
...
     modified_on timestamp DEFAULT current_timestamp,
-    deleted TINYINT(1) DEFAULT FALSE,
+    deleted BOOLEAN DEFAULT FALSE,
     created_by varchar(50),
     modified_by varchar(50),
     deleted_on timestamp NULL,
     deleted_by varchar(50),
     ext_id varchar(100),
-    ext_metadata json,
+    ext_metadata jsonb,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230619123601-create-question-options-up.sql:16]: jsonb

File: services/survey-service/migrations/sqls/20230621082309-create-question-templates-up.sql [hunk 5]
```diff
@@ -1,36 +1,34 @@
...
+CREATE OR REPLACE FUNCTION moddatetime()
+ RETURNS trigger
+ LANGUAGE plpgsql
+AS $function$
+BEGIN
+    NEW.modified_on = now();
+    RETURN NEW;
 END;
+$function$
+;
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230621082309-create-question-templates-up.sql:28]: why same function created again

File: services/survey-service/migrations/sqls/20230621082309-create-question-templates-up.sql [hunk 6]
```diff
@@ -1,36 +1,34 @@
...
+    deleted BOOLEAN DEFAULT FALSE,
     created_by varchar(50),
     modified_by varchar(50),
     deleted_on timestamp NULL,
     deleted_by varchar(50),
-    is_enable_weight TINYINT(1) DEFAULT FALSE,
+    is_enable_weight BOOLEAN DEFAULT FALSE,
     ext_id varchar(100),
-    ext_metadata json,
+    ext_metadata jsonb,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230621082309-create-question-templates-up.sql:15]: same

File: services/survey-service/migrations/sqls/20230621113225-create-template-questions-up.sql [hunk 7]
```diff
@@ -28,21 +28,19 @@ ALTER TABLE
...
+CREATE OR REPLACE FUNCTION moddatetime()
+ RETURNS trigger
+ LANGUAGE plpgsql
+AS $function$
+BEGIN
+    NEW.modified_on = now();
+    RETURN NEW;
 END;
+$function$
+;
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230621113225-create-template-questions-up.sql:41]: same

File: services/survey-service/migrations/sqls/20230621113225-create-template-questions-up.sql [hunk 8]
```diff
@@ -1,20 +1,20 @@
 CREATE TABLE template_questions (
-    id varchar(50) NOT NULL,
-    template_id varchar(50) NOT NULL,
-    question_id varchar(50) NOT NULL,
-    display_order INTEGER(100) NOT NULL,
-    is_mandatory boolean DEFAULT 0,
+    id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
+    template_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
+    question_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230621113225-create-template-questions-up.sql:4]: default value?

File: services/survey-service/migrations/sqls/20230621164240-create-survey-up.sql [hunk 9]
```diff
@@ -1,39 +1,41 @@
...
     start_date DATE,
     end_date DATE,
     status varchar(50) NOT NULL,
-    is_enable_weights TINYINT(1) DEFAULT FALSE,
-    survey_text LONGTEXT NULL,
-    base_survey_id varchar(50) NULL created_on timestamp DEFAULT current_timestamp,
+	is_periodic_reassessment BOOLEAN DEFAULT false,
+	recurrence_frequency varchar(50) NOT NULL,
+	recurrence_end_date DATE,
+	recurrence_end_after_occurrences INTEGER,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230621164240-create-survey-up.sql:11]: extra columns?

File: services/survey-service/migrations/sqls/20230621164240-create-survey-up.sql [hunk 10]
```diff
@@ -1,39 +1,41 @@
...
     modified_on timestamp DEFAULT current_timestamp,
-    deleted TINYINT(1) DEFAULT FALSE,
+    deleted BOOLEAN DEFAULT FALSE,
     created_by varchar(50),
     modified_by varchar(50),
     deleted_on timestamp NULL,
     deleted_by varchar(50),
     ext_id varchar(100),
-    ext_metadata json,
+    ext_metadata jsonb,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230621164240-create-survey-up.sql:23]: same

File: services/survey-service/migrations/sqls/20230621164240-create-survey-up.sql [hunk 11]
```diff
@@ -1,39 +1,41 @@
...
+CREATE OR REPLACE FUNCTION moddatetime()
+ RETURNS trigger
+ LANGUAGE plpgsql
+AS $function$
+BEGIN
+    NEW.modified_on = now();
+    RETURN NEW;
 END;
+$function$
+;
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230621164240-create-survey-up.sql:36]: same

File: services/survey-service/migrations/sqls/20230621164337-create-survey-questions-up.sql [hunk 12]
```diff
@@ -1,47 +1,31 @@
...
-    id varchar(50) NOT NULL,
-    survey_id varchar(50) NOT NULL,
-    question_id varchar(50) NOT NULL,
-    display_order INTEGER(100) NOT NULL,
-    is_mandatory TINYINT(1) DEFAULT FALSE,
-    dependent_on_question_id varchar(50) NULL,
-    `weight` DECIMAL(5, 2) DEFAULT 0.00,
+    id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
+    survey_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
+    question_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230621164337-create-survey-questions-up.sql:4]: dafault?

File: services/survey-service/migrations/sqls/20230621164337-create-survey-questions-up.sql [hunk 13]
```diff
@@ -1,47 +1,31 @@
...
+    display_order INTEGER NOT NULL,
+    is_mandatory BOOLEAN DEFAULT FALSE,
+    dependent_on_question_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230621164337-create-survey-questions-up.sql:7]: same default

File: services/survey-service/migrations/sqls/20230622111309-sections-up.sql [hunk 14]
```diff
@@ -1,35 +1,32 @@
...
     modified_on timestamp DEFAULT current_timestamp,
-    deleted TINYINT(1) DEFAULT FALSE,
+    deleted BOOLEAN DEFAULT FALSE,
     created_by varchar(50),
     modified_by varchar(50),
     deleted_on timestamp NULL,
     deleted_by varchar(50),
     ext_id varchar(100),
-    ext_metadata json,
+    ext_metadata jsonb,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230622111309-sections-up.sql:14]: same

File: services/survey-service/migrations/sqls/20230622111309-sections-up.sql [hunk 15]
```diff
@@ -1,35 +1,32 @@
...
+CREATE OR REPLACE FUNCTION moddatetime()
+ RETURNS trigger
+ LANGUAGE plpgsql
+AS $function$
+BEGIN
+    NEW.modified_on = now();
+    RETURN NEW;
 END;
+$function$
+;
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230622111309-sections-up.sql:27]: same

File: services/survey-service/migrations/sqls/20230622111907-survey-responders-up.sql [hunk 16]
```diff
@@ -22,31 +20,76 @@ CREATE TABLE survey_responders (
...
-    new.id = uuid();
+CREATE OR REPLACE FUNCTION moddatetime()
+ RETURNS trigger
+ LANGUAGE plpgsql
+AS $function$
+BEGIN
+    NEW.modified_on = now();
+    RETURN NEW;
+END;
+$function$CREATE TABLE survey_responders (
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230622111907-survey-responders-up.sql:41]: typo

File: services/survey-service/migrations/sqls/20230622111907-survey-responders-up.sql [hunk 17]
```diff
@@ -22,31 +20,76 @@ CREATE TABLE survey_responders (
...
+    COALESCE(first_name, '') ||
+    CASE
+        WHEN first_name IS NOT NULL AND last_name IS NOT NULL THEN ' '
+        ELSE ''
+    END ||
+    COALESCE(last_name, '')
+    ) STORED,
+    email varchar(150) NOT NULL,
+    user_id varchar(50) NULL,
+    survey_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230622111907-survey-responders-up.sql:55]: default

File: services/survey-service/migrations/sqls/20230622112026-survey-cycles-up.sql [hunk 18]
```diff
@@ -1,36 +1,33 @@
 CREATE TABLE survey_cycles (
-    id varchar(50) NOT NULL,
-    survey_id varchar(50) NOT NULL,
+    id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
+    survey_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230622112026-survey-cycles-up.sql:3]: default

File: services/survey-service/migrations/sqls/20230622112223-survey-cycle-responses-up.sql [hunk 19]
```diff
@@ -1,17 +1,17 @@
 CREATE TABLE survey_cycle_responses (
-    id varchar(50) NOT NULL,
+    id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
     survey_responder_id varchar(50) NOT NULL,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230622112223-survey-cycle-responses-up.sql:3]: will be uuid without default

File: services/survey-service/migrations/sqls/20230622112223-survey-cycle-responses-up.sql [hunk 20]
```diff
@@ -1,17 +1,17 @@
...
-    survey_cycle_id varchar(50) NOT NULL,
+    survey_cycle_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230622112223-survey-cycle-responses-up.sql:4]: remove default

File: services/survey-service/migrations/sqls/20230622112223-survey-cycle-responses-up.sql [hunk 21]
```diff
@@ -20,21 +20,18 @@ ALTER TABLE
...
+CREATE OR REPLACE FUNCTION moddatetime()
+ RETURNS trigger
+ LANGUAGE plpgsql
+AS $function$
+BEGIN
+    NEW.modified_on = now();
+    RETURN NEW;
 END;
+$function$
+;
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230622112223-survey-cycle-responses-up.sql:32]: same

File: services/survey-service/migrations/sqls/20230622112646-survey-response-details-up.sql [hunk 22]
```diff
@@ -1,26 +1,22 @@
+CREATE TYPE response_type_enum AS ENUM ('Drop Down','Multi Selection','Scale','Single Selection','Text');
+
 CREATE TABLE survey_response_details (
-    id varchar(50) NOT NULL,
-    survey_response_id varchar(50) NOT NULL,
-    question_id varchar(50) NOT NULL,
+    id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
+    survey_response_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
+    question_id uuid DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
```
Comment (yeshamavani) [inline services/survey-service/migrations/sqls/20230622112646-survey-response-details-up.sql:6]: default

**Review by yeshamavani — CHANGES_REQUESTED** [review]
should be on main schema

File: services/survey-service/migrations/sqls/20230619123543-create-questions-up.sql (hunk 2 above)
Comment (arpit1503khanna) [reply services/survey-service/migrations/sqls/20230619123543-create-questions-up.sql:23]: i don't think it will affect the functionality, because jsonb is an improvement over json in the way it stores data, but to be on the safe side I can remove it, if u say so

Comment (samarpan-b) [reply services/survey-service/migrations/sqls/20230619123543-create-questions-up.sql:23]: jsonb is better

File: services/survey-service/migrations/sqls/20230621082309-create-question-templates-up.sql (hunk 5 above)
Comment (arpit1503khanna) [reply services/survey-service/migrations/sqls/20230621082309-create-question-templates-up.sql:28]: will fix it

File: services/survey-service/migrations/sqls/20230621164240-create-survey-up.sql (hunk 9 above)
Comment (arpit1503khanna) [reply services/survey-service/migrations/sqls/20230621164240-create-survey-up.sql:11]: because in the subsequent statements it was creating index on these columns

File: services/survey-service/migrations/sqls/20230622112223-survey-cycle-responses-up.sql (hunk 19 above)
Comment (arpit1503khanna) [reply services/survey-service/migrations/sqls/20230622112223-survey-cycle-responses-up.sql:3]: ok, will fix it
