### PR TITLE
fix(authentication-service):provide support to manage tokens for user logging in and logging out via cognito

### LINKED ISSUE #1939: Authentication Service: Need support to manage tokens for user logging in via aws-cognito
**Describe the bug**
When a user logs in via Cognito , the tokens provided by the Cognito are not used , while issuing access tokens tokens using the refresh token. Instead the tokens are internally generated without any consent from cognito
in continuation - https://github.com/sourcefuse/loopback4-microservice-catalog/issues/1263

### PR DESCRIPTION
**Pull request by arpit1503khanna**
## Description
Provide support to manage tokens for user logging in and logging out via cognito

Fixes #1939 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by yeshamavani — APPROVED** [review]

**Comment by yeshamavani** [comment]
will be merged after https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1925

**Comment by yeshamavani** [comment]
@arpit1503khanna CI failing please check

File: services/authentication-service/src/modules/auth/controllers/logout.controller.ts [hunk 1]
```diff
@@ -348,6 +348,102 @@ export class LogoutController {
...
+      const basicAuth = Buffer.from(
+        `${process.env.COGNITO_AUTH_CLIENT_ID}:${process.env.COGNITO_AUTH_CLIENT_SECRET}`,
+      ).toString('base64');
+      const params = new URLSearchParams();
+      params.append('token', refreshTokenModel.externalRefreshToken);
+      params.append('client_id', `${process.env.COGNITO_AUTH_CLIENT_ID}`);
+      fetch(revokeUrl, {
+        method: 'POST',
+        headers: {
+          'Content-Type': 'application/x-www-form-urlencoded',
```
Comment (yeshamavani) [inline services/authentication-service/src/modules/auth/controllers/logout.controller.ts:412]: content type

**Review by yeshamavani — CHANGES_REQUESTED** [review]

File: services/authentication-service/src/modules/auth/controllers/logout.controller.ts (hunk 1 above)
Comment (yeshamavani) [reply services/authentication-service/src/modules/auth/controllers/logout.controller.ts:412]: please make the appropriate changes everywhere

**Comment by yeshamavani** [comment]
there are sonar issues as well

**Review by yeshamavani — APPROVED** [review]
