### PR TITLE
refactor(authentication-service): fix sonar issues

### LINKED ISSUE #251: Sonar is RED
**Describe the bug**
Sonar issues

https://sonarcloud.io/project/issues?id=sourcefuse_loopback4-microservice-catalog&resolved=false

**Expected behavior**
Sonar needs to be green

### PR DESCRIPTION
**Pull request by akshatdubeysf**
## Description

Fixed issues reported by sonar cloud scan.

BREAKING CHANGE:

changed client_id and client_secret to clientId and clientSecret in login-request dto and client-auth-req dto

Fixes #251 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [X] Performed a self-review of my own code
- [X] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: sandbox/auth-multitenant-example/src/controllers/todo.controller.ts [hunk 1]
```diff
@@ -119,30 +118,30 @@ export class TodoController {
   @authenticate(STRATEGY.BEARER, {
     passReqToCallback: true,
   })
-  @authorize({permissions: [PermissionKey.TodoOwner]})
+  @authorize({ permissions: [PermissionKey.TodoOwner] })
```
Comment (samarpan-b) [inline sandbox/auth-multitenant-example/src/controllers/todo.controller.ts:121]: run prettier

**Review by samarpan-b — CHANGES_REQUESTED** [review]
