### PR TITLE
fix(cli): Include the update of loopback packages via sourceloop cli

### LINKED ISSUE #1023: Include the update of loopback packages via sourceloop cli
**Describe the bug**
Include the update of loopback packages via sourceloop cli 

**To Reproduce**
Currently the sourceloop cli makes a super call to loopback cli for update and then updates the sourceloop packages.

**Expected behavior**
Now we will directly update loopback and sourceloop packages simultaneously.

### PR DESCRIPTION
**Pull request by yeshamavani**
gh-1023

## Description

Include the update of loopback packages via sourceloop cli
=> Currently the sourceloop cli makes a super call to loopback cli for update and then updates the sourceloop packages.
=> Now we will directly update loopback and sourceloop packages simultaneously.

Fixes #1023

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/cli/src/generators/update/index.ts [hunk 1]
```diff
@@ -240,14 +211,14 @@ export default class UpdateGenerator extends BaseUpdateGenerator<UpdateOptions>
     this.log(
       chalk.red('Upgrading dependencies may break the current project.'),
     );
-    this.fs.writeJSON(this.destinationPath(packageJsonFile), packageJs);
+    fs.writeFileSync(
```
Comment (akshatdubeysf) [inline packages/cli/src/generators/update/index.ts:214]: We should show the user which deps will be replaced. This log should be shown once before any services' json is changed

**Review by akshatdubeysf — CHANGES_REQUESTED** [review]

File: packages/cli/src/generators/update/index.ts (hunk 1 above)
Comment (yeshamavani) [reply packages/cli/src/generators/update/index.ts:214]: we show the list using _printDepsToUpdate()

**Review by akshatdubeysf — APPROVED** [review]
