### PR TITLE
fix(deps): fix sonar issues

### LINKED ISSUE #2126: Fix Sonar Issues
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Tyagi-Sunny**
fix sonar issues

2126

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2126 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/cli/src/generators/cdk/index.ts [hunk 1]
```diff
@@ -195,51 +195,61 @@ export default class CdkGenerator extends BaseGenerator<CdkOptions> {
...
+        this.options.relativePathToApp,
+      );
 
-    const isDefaultExport = await this._isDefaultExport(
-      this.options.applicationClassName!,
-      this.options.relativePathToApp!,
-    );
+      const appImportPath = this._getAppImportPath(
+        this.options.relativePathToApp,
+      );
```
Comment (yeshamavani) [inline packages/cli/src/generators/cdk/index.ts:209]: why using an if else block

File: packages/cli/src/generators/cdk/index.ts [hunk 2]
```diff
@@ -15,9 +15,9 @@ import {
   Project,
   PropertyAssignmentStructure,
 } from 'ts-morph';
-import {BaseGenerator} from '../../base-generator';
-import {IacList} from '../../enum';
-import {CdkOptions} from '../../types';
+import { BaseGenerator } from '../../base-generator';
+import { IacList } from '../../enum';
+import { CdkOptions } from '../../types';
```
[the remark this answers is not in the document]
Comment (Tyagi-Sunny) [reply packages/cli/src/generators/cdk/index.ts:20]: did by prettier:fix

File: packages/cli/src/generators/cdk/index.ts (hunk 1 above)
Comment (Tyagi-Sunny) [reply packages/cli/src/generators/cdk/index.ts:209]: type of  this.options.applicationClassName is string | undefined, but _isDefaultExport require arguement to be string only
