### PR TITLE
fix(cli): add commit config to cli

### LINKED ISSUE #790: @sourceloop/cli generated scaffold has incorrect commitizen config
**Describe the bug**
A Scaffold generated by the sourceloop/cli has missing commitlint config and cz-config.

**To Reproduce**
1. Generate a scaffold using sourceloop/cli
2. Try to commit
3. The commitlint says config is missing

**Expected behavior**
A default config should be provided

### PR DESCRIPTION
**Pull request by yeshamavani**
gh-790

## Description

scaffold created through was missing the commit config added commitlint files.
Fixes #790 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [X] Performed a self-review of my own code
- [X] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/cli/src/generators/scaffold/index.ts [hunk 1]
```diff
@@ -19,6 +19,19 @@ export default class ScaffoldGenerator extends BaseGenerator<ScaffoldOptions> {
     }
   }
 
+  async ticketNumberPrompt() {
+    if (!this.options.ticketPrefix) {
+      const {ticketPrefix} = await this.prompt([
+        {
+          type: 'input',
+          name: 'ticketPrefix',
+          message: 'Prefix while commiting changes to git:',
```
Comment (akshatdubeysf) [inline packages/cli/src/generators/scaffold/index.ts:28]: Just ask for issue prefix, as the prefix may not be related to github at all

**Review by akshatdubeysf — APPROVED** [review]

File: packages/cli/src/generators/scaffold/index.ts (hunk 1 above)
Comment (yeshamavani) [reply packages/cli/src/generators/scaffold/index.ts]: done
