### PR TITLE
fix(ocr-service): prettier and lint issue

### LINKED ISSUE #774: Fix Prettier error
**Describe the bug**
Fixed Prettier error for ocr-service and ocr-s3-service.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by kundan-sf**
## Description

Fix prettier issue for ocr-s3-service and ocr-service

Fixes #774 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: services/ocr-s3-service/src/types.ts [hunk 1]
```diff
@@ -1 +1,96 @@
...
+  Size?: number;
+  StorageClass?: ObjectStorageClass | string;
+  Owner?: Owner;
+}
+
+/* eslint-disable  @typescript-eslint/no-explicit-any */
+type Blob = any;
+
+/* eslint-disable  @typescript-eslint/no-explicit-any */
+type ReadableStream = any;
```
Comment (akshatdubeysf) [inline services/ocr-s3-service/src/types.ts:41]: this should be part of typescript?

**Review by akshatdubeysf — APPROVED** [review]

File: services/ocr-s3-service/src/types.ts (hunk 1 above)
Comment (kundan-sf) [reply services/ocr-s3-service/src/types.ts:41]: yes

**Review by akshatdubeysf — APPROVED** [review]
