### PR TITLE
fix(cli):  lambda files should only be generated if opted for cdk

### LINKED ISSUE #1698: Sourceloop CLI : lambda files should only be generated if opted for cdk
**Describe the bug**
1. lambda files should only be generated if opted for cdk
2. should not be present in the migrations folder.

**To Reproduce**
1. sl scaffold
2. sl microservice
3. go to migrations folder
4. npm run db:migrate
5. observe the error

**Expected behavior**
db:migrate should run errorless

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Tyagi-Sunny**
lambda files should only be generated if opted for cdk

gh-1698

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1698 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/cli/src/generators/microservice/index.ts [hunk 1]
```diff
@@ -639,7 +639,12 @@ export default class MicroserviceGenerator extends AppGenerator<MicroserviceOpti
       } else {
         // do nothing
       }
+      this.fs.delete(join(MIGRATION_FOLDER, name, 'migrations', 'lambda.js'));
+      this.log(
+        this.destinationPath(join(MIGRATION_FOLDER, name, 'migrations', 'lambda.js', 'sunny')),
+      );
```
Comment (yeshamavani) [inline packages/cli/src/generators/microservice/index.ts:645]: remove name

**Review by yeshamavani — CHANGES_REQUESTED** [review]

File: packages/cli/src/generators/microservice/index.ts (hunk 1 above)
Comment (Tyagi-Sunny) [reply packages/cli/src/generators/microservice/index.ts]: done

File: packages/cli/src/generators/microservice/index.ts [hunk 2]
```diff
@@ -639,7 +639,12 @@ export default class MicroserviceGenerator extends AppGenerator<MicroserviceOpti
       } else {
         // do nothing
       }
+      this.fs.delete(join(MIGRATION_FOLDER, name, 'migrations', 'lambda.js'));
+      this.log(
+        this.destinationPath(join(MIGRATION_FOLDER, name, 'migrations', 'lambda.js')),
+      );
```
Comment (yeshamavani) [inline packages/cli/src/generators/microservice/index.ts:645]: ??
if this file is not needed then why are we creating it first place 
it should be created only if the user opts for it

Comment (Tyagi-Sunny) [reply packages/cli/src/generators/microservice/index.ts:645]: The file is located in the 'service/migration' folder. Migrations are copied from there. So, whether a user opts for CDK  or not, 'lambda.js' will be created in the 'package/migration/example-service' directory. The reason for keeping 'lambda.js' in the 'service/migration' folder is that 'lambda.js' is a fixed file required for running migrations on Lambda.

**Review by yeshamavani — APPROVED** [review]
