### PR TITLE
fix(all-services): update migration.js to run migration on post install

### LINKED ISSUE #2003: Update migration.js for every service
**Describe the bug**
User not able to generate migration manually as mentioned in readme
image

**To Reproduce**
1. create a lb4 app
2. follow the readme to implement service
3. do npm i

**Expected behavior**
migration should be created after doing npm i automatically

**Screenshots**
but getting above added error

### PR DESCRIPTION
**Pull request by Tyagi-Sunny**
## Description

update migration.js to run migration on post install

Fixes #2003 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: services/audit-service/migration.js [hunk 1]
```diff
@@ -34,15 +34,22 @@ if (isLocal) {
     errorOnMissing: true,
     includeProcessEnv: true,
   });
-  const dbmigrate = DBMigrate.getInstance(true);
+  // Initialize db-migrate with correct migration directory and database config path
+  const dbmigrate = DBMigrate.getInstance(true, {
+    config: path.join('migrations', 'pg', 'database.json'),
```
Comment (yeshamavani) [inline services/audit-service/migration.js:39]: why default pg what about mysql
